import { DEFAULT_STORE_ID } from "./storeConfig";

export const specials = [
  {
    id: "happy-hour-edibles",
    storeId: DEFAULT_STORE_ID,
    title: "Happy Hour Edibles",
    details: "Save 15% on all gummies and chocolates before 5 PM.",
    tag: "15% Off",
    type: "price_override",
    productIds: ["mango-gummies", "midnight-chews"],
  },
  {
    id: "bogo-pre-rolls",
    storeId: DEFAULT_STORE_ID,
    title: "BOGO Pre-Rolls",
    details: "Buy one infused pre-roll and unlock a second for half price.",
    tag: "Pickup Favorite",
    type: "bogo",
    productIds: ["moonberry-infused"],
  },
  {
    id: "vape-bundle",
    storeId: DEFAULT_STORE_ID,
    title: "Vape Bundle",
    details: "Two 1g carts for $58 when added to the same preorder.",
    tag: "Bundle",
    type: "bundle",
    productIds: ["pineapple-cart", "gelato-cart"],
  },
];

export const menuSections = [
  {
    id: "flower",
    storeId: DEFAULT_STORE_ID,
    title: "Flower",
    description: "Top shelf eighths and quick-pick half ounce prepacks.",
    items: [
      {
        id: "sunset-runtz",
        productId: "sunset-runtz",
        storeId: DEFAULT_STORE_ID,
        category: "flower",
        name: "Sunset Runtz",
        strain: "Hybrid",
        size: "3.5g",
        thc: "29%",
        price: 38,
        specialPrice: 34,
        specialLabel: "Happy Hour price",
      },
      {
        id: "north-shore-og",
        productId: "north-shore-og",
        storeId: DEFAULT_STORE_ID,
        category: "flower",
        name: "North Shore OG",
        strain: "Indica",
        size: "7g",
        thc: "31%",
        price: 62,
      },
      {
        id: "citrus-diesel",
        productId: "citrus-diesel",
        storeId: DEFAULT_STORE_ID,
        category: "flower",
        name: "Citrus Diesel",
        strain: "Sativa",
        size: "3.5g",
        thc: "26%",
        price: 35,
      },
    ],
  },
  {
    id: "edibles",
    storeId: DEFAULT_STORE_ID,
    title: "Edibles",
    description: "Fast-moving pickup options for consistent dosing.",
    items: [
      {
        id: "mango-gummies",
        productId: "mango-gummies",
        storeId: DEFAULT_STORE_ID,
        category: "edibles",
        name: "Mango Lift Gummies",
        strain: "Sativa",
        size: "100mg",
        thc: "10 x 10mg",
        price: 24,
        specialPrice: 20,
        specialLabel: "Happy Hour price",
      },
      {
        id: "midnight-chews",
        productId: "midnight-chews",
        storeId: DEFAULT_STORE_ID,
        category: "edibles",
        name: "Midnight Chews",
        strain: "Indica",
        size: "100mg",
        thc: "10 x 10mg",
        price: 22,
        specialPrice: 19,
        specialLabel: "Happy Hour price",
      },
    ],
  },
  {
    id: "vapes",
    storeId: DEFAULT_STORE_ID,
    title: "Vapes",
    description: "Staff-ready cartridges prepacked for express pickup.",
    items: [
      {
        id: "pineapple-cart",
        productId: "pineapple-cart",
        storeId: DEFAULT_STORE_ID,
        category: "vapes",
        name: "Pineapple Express Cart",
        strain: "Sativa",
        size: "1g",
        thc: "88%",
        price: 32,
        bundleEligible: true,
      },
      {
        id: "gelato-cart",
        productId: "gelato-cart",
        storeId: DEFAULT_STORE_ID,
        category: "vapes",
        name: "Gelato Ice Cart",
        strain: "Hybrid",
        size: "1g",
        thc: "84%",
        price: 32,
        bundleEligible: true,
      },
    ],
  },
  {
    id: "pre-rolls",
    storeId: DEFAULT_STORE_ID,
    title: "Pre-Rolls",
    description: "Single sticks for fast in-and-out pickup.",
    items: [
      {
        id: "moonberry-infused",
        productId: "moonberry-infused",
        storeId: DEFAULT_STORE_ID,
        category: "pre-rolls",
        name: "Moonberry Infused Pre-Roll",
        strain: "Hybrid",
        size: "1g",
        thc: "41%",
        price: 18,
        specialLabel: "Second one 50% off",
      },
      {
        id: "lemon-spark",
        productId: "lemon-spark",
        storeId: DEFAULT_STORE_ID,
        category: "pre-rolls",
        name: "Lemon Spark Pre-Roll",
        strain: "Sativa",
        size: "1g",
        thc: "24%",
        price: 11,
      },
    ],
  },
];
